const products = [
    {
        id: 1,
        name: 'iphone 13 pro',
        description: ' This is iphone 13 pro ',
        type: 'phone',
        capasity: '128',
        price: '800',
        images: 'images/iphone.jpg',
    },
    {
        id: 2,
        name: 'iphone 9 ',
        description: ' This is iphone 9 ',
        type: 'phone',
        capasity: '128',
        price: '700',
        images: 'images/iphone1.jpg',
    },
    {
        id: 3,
        name: 'iphone 10 pro',
        description: ' This is iphone 10 pro ',
        type: 'phone',
        capasity: '128',
        price: '900',
        images: 'images/iphone2.jpg',
    },
    {
        id: 4,
        name: 'iphone 12 pro',
        description: ' This is iphone 12 pro ',
        type: 'phone',
        capasity: '64',
        price: '1500',
        images: 'images/iphone3.jpg',
    },
    {
        id: 5,
        name: 'iphone 13 ',
        description: ' This is iphone 13 ',
        type: 'phone',
        capasity: '128',
        price: '2200',
        images: 'images/iphone.jpg',
    },
    {
        id: 6,
        name: 'iphone 11 pro',
        description: ' This is iphone 11 pro ',
        type: 'phone',
        capasity: '256',
        price: '2000',
        images: 'images/iphone1.jpg',
    },
]

export default products
